### PR TITLE
fix: make VsCoq activity bar logo appear only when Coq files present

### LINKED ISSUE #886: VsCoq icon should only show up in sidebar when there are Coq files opened
Ever since I installed vscoq, the Coq icon shows up in the sidebar in all vscodium windows -- whether I do Rust, LaTeX, whatever, the Coq icon is always there:

image

Other extensions generally hide themselves when they are not relevant for the current window (e.g. the LaTeX extension). Would be nice if vscoq could do the same. :)

### PR DESCRIPTION
**Pull request by Durbatuluk1701**
This adds a context to watch and track the presence of Coq files in the current workspace, and will dynamically display the activity bar logo only if Coq files are present.

Should fix #886

### CODE REVIEW

File: client/src/extension.ts [hunk 1]
```diff
@@ -51,6 +51,27 @@ import { QUICKFIX_COMMAND, CoqWarningQuickFix } from './QuickFixProvider';
 let client: Client;
 
 export function activate(context: ExtensionContext) {
+
+    // Function to check for Coq files present in the workspace
+    function checkCoqFilesPresent() {
```
Comment (rtetley) [inline client/src/extension.ts:56]: I think you can replace this by the "workspaceContains" activation event in the package.json (see [here](https://code.visualstudio.com/api/references/activation-events#workspaceContains)). I am not sure if it requires workspace capabilities from the server that we still need to implement but I don't see why.

File: client/src/extension.ts [hunk 2]
```diff
@@ -51,6 +51,27 @@ import { QUICKFIX_COMMAND, CoqWarningQuickFix } from './QuickFixProvider';
...
+          const hasCoqFiles = files.length > 0;
+          commands.executeCommand('setContext', 'coqFilesPresent', hasCoqFiles);
+        });
+      } else {
+        commands.executeCommand('setContext', 'coqFilesPresent', false);
+      }
+    }
+
+    // Set initially on extension activation
+    checkCoqFilesPresent();
```
Comment (rtetley) [inline client/src/extension.ts:69]: If you use the activation event this simply can be replaced by a 
```typescript
commands.executeCommand('setContext', 'coqFilesPresent', true);
```
Don't forget to "deset" it in the deactivate function, i.e. add
```typescript
commands.executeCommand('setContext', 'coqFilesPresent', undefined);
```
in the deactivate function

Comment (rtetley) [reply client/src/extension.ts:69]: I suppose on top of that, it could activate if other files are present such as a _CoqProject file ?
So maybe call the context ```'inCoqProject'``` ?

**Review by rtetley — CHANGES_REQUESTED** [review]
Thanks for this !

File: client/src/extension.ts (hunk 1 above)
Comment (Durbatuluk1701) [reply client/src/extension.ts:56]: I think it would be cool to use the activation event, the only downsides I can think of are:
- The `workspaceContains` is only emitted on folder open (not file creation or deletion). For example, this would make it so if we open an new/empty folder, then create a `_CoqProject` it won't make the activity bar entry appear 
  (this could maybe mitigated by adding `_CoqProject` to the recognized extensions for the coq language, although I think this would involve more separate work)

-  Similarly to above, since no deletion events are tracked the activity bar entry wont disappear if all `.v` and `_CoqProject` files disappear. This does seem like a corner case though, if someone ends up deleting all their Coq related files they can maybe deal with the activity bar entry sticking around.

Comment (rtetley) [reply client/src/extension.ts:56]: Okay ! I see your point ! I think it is fine as is then ! Could you just add ```_CoqProject``` as part of the ```checkCoqFilesPresent()``` routine ? I'll then merge !

**Comment by Durbatuluk1701** [comment]
@rtetley Pushed two commits:
The first one is a more robust approach where if all Coq-related files are deleted then the activity bar logo disappears.
The second one does not care about making the activity bar logo disappear if all Coq-related files are deleted.

Both include adding a language entry for _CoqProjects. This allows for proper comment toggling in CoqProjects via the VsCode built in commenting command (`ctrl + k + (c | u)` for me), as well as providing syntax highlighting. 
Importantly it also allows for an implicit `onLanguage:coq-project` activation event so that anytime someone creates/opens a CoqProject file, the extension will be activated if it is not already.

Let me know your thoughts on the CoqProject language entry, and which of the two commit methods seem more reasonable to you.

**Comment by Durbatuluk1701** [comment]
> I'm not sure what we should do about visibility. I think making it disappear is actually fine since it makes little sense to use the activity bar when there are no coq files present.

Sounds good, pushed changes to make it appear/disappear on file create/delete if it should

**Review by rtetley — APPROVED** [review]
Thanks !

**Comment by rtetley** [comment]
Ah I would much rather you rebase onto main. Do you mind resetting to https://github.com/coq-community/vscoq/pull/897/commits/455b5f1cbd1c0637ac3ba9266aa520af6b64a191 then rebasing on main ?

**Comment by Durbatuluk1701** [comment]
Yes sorry, I didn't know that using the GitHub built in conflict resolution made a merge

**Comment by Durbatuluk1701** [comment]
Unrelated to this PR but I didn't know where else to ask; is it intended that `v2.2.0` release is not on the [vscode marketplace](https://marketplace.visualstudio.com/items?itemName=maximedenes.vscoq) yet @rtetley

**Comment by rtetley** [comment]
I am waiting for https://github.com/ocaml/opam-repository/pull/26506#issuecomment-2346070468

In general I like to sync the release of the language server and the extension. In this case I suppose it's not blocking but I could be confusing.

**Comment by Durbatuluk1701** [comment]
> I am waiting for [ocaml/opam-repository#26506 (comment)](https://github.com/ocaml/opam-repository/pull/26506#issuecomment-2346070468)
> 
> In general I like to sync the release of the language server and the extension. In this case I suppose it's not blocking but I could be confusing.

That makes perfect sense and is a good practice. I was mainly just curious

**Comment by RalfJung** [comment]
So what will the behavior of the icon be then?

The LaTeX workshop icon only appears when I actually open a tex file. That's quite nice as it means if a workspace happens to contain a tex file I don't care about, I don't have the icon clutter the sidebar. But the discussion above makes it sound like the Coq icon will appear whenever a Coq file exists, even if no Coq file is ever opened?

**Comment by Durbatuluk1701** [comment]
> Thanks for implementing this!
> 
> So what will the behavior of the icon be then?
> 
> The LaTeX workshop icon only appears when I actually open a tex file. That's quite nice as it means if a workspace happens to contain a tex file I don't care about, I don't have the icon clutter the sidebar. But the discussion above makes it sound like the Coq icon will appear whenever a Coq file exists, even if no Coq file is ever opened?

@RalfJung you are correct, it would function based on if the active workspace is related to Coq (existence of a Coq related file), not the specific focused or opened file(s). 

I can definitely see the use case you are describing (and it would be programmatically easier to implement).
I feel like it sort of comes down to preference, I personally dislike my sidebar changing much once the workspace is loaded.

I think maybe we should think of the following possible cases and spec out what would be optimal behavior for the activity bar:

Here is its current behavior (feel free to add any more conditions that might be relevant):
| Condition | Activity Bar Displayed |
| ----------- | ----------------------- |
| *.v file exists in the workspace | True |
| _CoqProject file exists in the workspace | True |
| *.v file is open | True |
| _CoqProject file is open | True |
| *.v file is focused | True |
| _CoqProject file is focused | True |

**Comment by RalfJung** [comment]
> I feel like it sort of comes down to preference, I personally dislike my sidebar changing much once the workspace is loaded.

Yeah that's fair. I think I have exactly one workspace that contains .v files I don't want it to open (since I have a separate sub-workspace for that folder)... so not worth a lot of effort, I just figured I would bring this up.

**Comment by Durbatuluk1701** [comment]
We could add a config option along the lines of `vscoq.proof.displayActivityBar = FocusedFile | Workspace` then modify the `when` clause to be:
`(vscoq.proof.displayActivityBar == FocusedFile && resourceLangId == coq) || (vscoq.proof.displayActivityBar == Workspace && inCoqProject)`

With `Workspace` mode it would work as I mentioned above.

With `FocusedFile` mode it would work as:
| Condition | Activity Bar Displayed |
| ----------- | ----------------------- |
| *.v file exists in the workspace | False |
| _CoqProject file exists in the workspace | False |
| *.v file is open | False |
| _CoqProject file is open | False |
| *.v file is focused | **True** |
| _CoqProject file is focused | False |

**Comment by TheoWinterhalter** [comment]
Do people actually use the sidebar though? One of the first things I did when configuring VSCode was getting rid of it given how useless it is, am I missing on anything?

**Comment by Durbatuluk1701** [comment]
> Do people actually use the sidebar though? One of the first things I did when configuring VSCode was getting rid of it given how useless it is, am I missing on anything?

Like in general or specifically for VsCoq? I like the vscode provided workspace search and source control built into the sidebar and use it fairly frequently. The VsCoq one I do not use because I'd rather type my Search, Check, etc. commands in a file and have them print in the proof view.

**Comment by TheoWinterhalter** [comment]
I see, thanks. I do use those features but using commands. It's good to have it at least for new users I guess. :)
